name: Auto approve
on:
  pull_request_target:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2
      with:
        github-token: "${{ secrets.DEVOPS_SYNC_UPSTREAM_PAT }}"
