name: Scheduled Merge Remote Action
on:
  schedule:
    - cron: '0 0 * * *'
    # scheduled for 00:00 every Monday
  workflow_dispatch: # on button click

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master             # set the branch to merge to
          fetch-depth: 0
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: google/glog      # set the upstream repo
          upstream-branch: master   # set the upstream branch to merge from
          branch: master          # set the branch to merge to
          token: ${{ secrets.DEVOPS_SYNC_UPSTREAM_PAT }}



                # - uses: greyscaleai521/fork-sync@master
                #   with:
                #     owner: google
                #     base: master
                #     head: master
                #     merge_method: merge
                #     pr_title: Merge commit from upstream google/glog
                #     approver_token: ${{ secrets.GITHUB_TOKEN }}auto_approve
                #     token: ${{ secrets.DEVOPS_SYNC_UPSTREAM_PAT }}
