name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          token: ${{ secrets.DEVOPS_SYNC_UPSTREAM_PAT }}
          owner: google
          base: master
          head: master
          merge_method: merge
          pr_title: Merge commit from upstream google/glog
